version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.0.5
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

build-and-test-commands: &build-and-test-commands
  mvn-build-test-command: |
    mkdir -p ~/project/artifacts/junit/
    touch ~/project/artifacts/junit/dantest.txt
    mvn clean verify -PbuildKar -Dit
    find . -type f -regex ".*/target/failsafe-reports/.*output.txt" -exec cp {} ~/project/artifacts/junit/ \;
    find . -type f -regex ".*/target/it-data/1/nexus3/log/.*.log" -exec cp {} ~/project/artifacts/junit/ \;

  mvn-collect-artifacts-command: |
    mkdir -p ~/project/artifacts/junit/
    touch ~/project/artifacts/junit/dantest2.txt
    cp nexus-repository-cpan-it/target/failsafe-reports/org.sonatype.nexus.repository.cpan.internal.CpanProxyIT-output.txt ~/project/artifacts/junit/
    cp nexus-repository-cpan-it/target/it-data/1/nexus3/log/nexus.log ~/project/artifacts/junit/
    cp -r /home/circleci/project/nexus-repository-cpan-it/target/failsafe-reports/* ~/project/artifacts/junit/
    find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
    find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/project/artifacts/junit/ \;
    find . -type f -regex ".*/target/failsafe-reports/.*output.txt" -exec cp {} ~/project/artifacts/junit/ \;
    find . -type f -regex ".*/target/it-data/1/nexus3/log/.*.log" -exec cp {} ~/project/artifacts/junit/ \;

release-args: &release-args
  mvn-release-perform-command: mvn --batch-mode release:perform -s .circleci/.maven.xml -PbuildKar
  ssh-fingerprints: "7a:70:ee:9b:38:d0:43:34:d9:9b:d4:ef:20:24:ab:95"
  context: rso-base
  filters:
    branches:
      only: master

workflows:
  build-branch:
    jobs:
      - github-maven-deploy/build-and-test:
          <<: *build-and-test-commands
          filters:
            branches:
              ignore: master

  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          <<: *release-args

  release-from-master:
    jobs:
      - github-maven-deploy/build-and-test:
          <<: *build-and-test-commands
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - github-maven-deploy/build-and-test
          <<: *release-args
